services:
  frontend:
    image: manim-frontend
    user: 0
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./videos:/videos
    networks:
      - net

  manim:
    image: manim-engine
    user: 0
    build: 
      context: ./manim
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./manim:/manim
      - ./videos:/videos
    networks:
      - net
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

networks:
  net:
    driver: host